### ISSUE TITLE
RuntimeError: Invalid settings file [settings]

### ISSUE THREAD

**Issue by shxnzxxn** [notexactlyawe/abracadabra#39]
While running song_recognizer initialise, I got an error : Invalid settings file [settings]
Also, hash.db is not create automatically.

**Comment by imsomdev** [comment]
What was the solution?

**Comment by shxnzxxn** [comment]
> What was the solution?
> 
> 

You have to append a system path like this.

sys.path.append('/home/os_202000828/Desktop/abracadabra/abracadabra')



More information, you can see this blog. If you want to ask about this please comment this issue or email to me skj4244@naver.com

**Comment by imsomdev** [comment]
which blog?

**Comment by imsomdev** [comment]
Actually im not able to initialise? Throwing some errors

**Comment by shxnzxxn** [comment]
Sorry to my mistake.

문제해결 | 샤잠(shazam) 노래인식을 구현한 abracadabra 사용하기 - https://splendidlolli.tistory.com/m/597

This blog written by Korean. If you want to translate to English, Use Translation.

You have to know that our problem is the missing path about module.

**Comment by imsomdev** [comment]
That issue is fixed, but when ever im trying to create an api using this package its not starting the server do you have any idea about this ?

**Comment by shxnzxxn** [comment]
when i used this api in the past, i couldn't catch any issue you said.

If you have an message about error, show me full message about that.

**Comment by imsomdev** [comment]
No, it's perfectly working. Thanks for your quick response.
